FROM ghcr.io/salopensource/sal-saml:latest
MAINTAINER Graham Gilbert <graham@grahamgilbert.com>

RUN apt-get update && apt-get install -y python3-setuptools python3-dev libxmlsec1-dev libxml2-dev xmlsec1 python3-pip
RUN pip install -U setuptools
RUN pip install djangosaml2==0.18.1

ADD attributemaps /home/app/sal/sal/attributemaps
RUN mv /home/app/sal/sal/urls.py /home/app/sal/sal/origurls.py
ADD urls.py /home/app/sal/sal/urls.py
